# Generated by Django 3.2.4 on 2021-06-13 09:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_student_birthdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='enroll_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='student',
            name='graduate_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
