# Generated by Django 3.2.4 on 2021-06-16 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_auto_20210613_1123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='graduate_date2',
        ),
    ]
