# Generated by Django 3.2.4 on 2021-06-16 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_student_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='age',
        ),
    ]
